import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { api } from "~/utils/api";
import Pretty_JSON from "~/components/pretty_json";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#E5DDC8] to-[#01949A]">
        <div className="m-5 flex h-24 w-11/12 items-center justify-center rounded-lg border-indigo-600 bg-[#004369] text-4xl text-[#e5ddc8]">
          {"{JSON Pretty-fy}"}
        </div>
        <div className="m-5 h-full w-11/12 overflow-y-auto border-2 border-white">
          <Pretty_JSON />
        </div>
      </main>
    </>
  );
}
